import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans_JP } from "next/font/google";
import {
  ClerkProvider,
} from '@clerk/nextjs'


const notoSansJP = Noto_Sans_JP({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  preload: true,
})

export const metadata: Metadata = {
  title: "ai-image-generator",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // clerkの最新Verはサインアウト後の遷移先は以下のように指定する。（.envに定義しても効かない）
    <ClerkProvider afterSignOutUrl="/dashboard">
      <html lang="ja">
        <body
          className={`${notoSansJP.className} antialiased`}
        >
          {children}
        </body>
      </html>
      </ClerkProvider>
  );
}
